### ISSUE TITLE
SD DDP Seems to be Holding Down the Ability for a Physical DDP to FF or RR

### ISSUE THREAD

**Issue by shawnmerrick** [epearsoe/Coleco-ADAM-SD-DDP#3] opened 2022-02-19 19:20 UTC
Hello Eric,

Encountered this issue copying from source SD-DDP2 center directory image to destination physical DDP1 with center directory tape.

Use any EOS or CP/M SD-DDP image and a blank center directory tape.  Boot File Manager v3 (from ADE D1), TURN OFF expansion RAM in File Manager menu.  Select MEDIA FUNCTION, COPY BLOCKS.  Source TAPE B, SD-DDP2, start at 0, 256 blocks.  Dest physical TAPE A, DDP1, start block 0.

Reading source into buffer OK up to 33 blocks.  First attempt writing to physical DDP1 then loses it's mind slowly seeking endlessly.  Works perfectly when both DDP are physical drives.

Tested repeatedly and confirmed findings with another person.  SD DDP seems to be holding down the ability for the physical DDP to FF or RR.

Love this project 100%.  Just awesome for the community.  THANK YOU!

     Shawn Merrick
     shawnmerrick@hotmail.com

**Comment by JohnLundy** [comment] 2022-02-20 14:55
I’m also able to duplicate the issue. I’ve always utilized RAM expansion (256K or higher) while using FM3 and never noticed this. It appears the problem is whenever RAM expansion is not used and can’t completely read in the whole tape data in and then completely write it to physical media. Without having expansion RAM, the SD DDP is interfering with the ability for the physical drive to FF or RR, not sure which one or possibly both during the copy process. When this issue occurs, the SD DDP displays “stop98” and nothing else. Interestingly, a way I discovered to get it past this point is to hit the reset button on the SD DDP while FM3 is trying to write to the physical tape followed by mounting the same image being copied again. It will then do the same problem again, displaying “stop” and a block number again and doing the same reset process over and over until a full copy is made. It doesn’t appear to be releasing itself correctly like it does when a complete copy to RAM is performed. I hope this helps explain it in greater detail.

**Comment by epearsoe** [comment] 2022-02-28 16:54
Verified the issue and resolved in SD DDP firmware version 1.6.  Fix verified by John Lundy.  Following the instructions in "Bootloading and Programming the ATMEGA2560.pdf" under "SD DDP Programming Instructions" using the ADAM_DDP_SD_Drive_Int_Power_1_6.ino.hex to update your SD DDP.

**Closed as completed by epearsoe** 2022-02-28 16:54 UTC
